function varargout = ArticulatedBodyAlgorithm(varargin)
<<<<<<< HEAD
  [varargout{1:nargout}] = iDynTreeMEX(1284, varargin{:});
=======
  [varargout{1:nargout}] = iDynTreeMEX(1262, varargin{:});
>>>>>>> Add autogenerated bindings
end
