classdef ArticulatedBodyAlgorithmInternalBuffers < SwigRef
  methods
    function this = swig_this(self)
      this = iDynTreeMEX(3, self);
    end
    function self = ArticulatedBodyAlgorithmInternalBuffers(varargin)
      if nargin==1 && strcmp(class(varargin{1}),'SwigRef')
        if ~isnull(varargin{1})
          self.swigPtr = varargin{1}.swigPtr;
        end
      else
<<<<<<< HEAD
        tmp = iDynTreeMEX(1262, varargin{:});
=======
        tmp = iDynTreeMEX(1240, varargin{:});
>>>>>>> Add autogenerated bindings
        self.swigPtr = tmp.swigPtr;
        tmp.SwigClear();
      end
    end
    function varargout = resize(self,varargin)
<<<<<<< HEAD
      [varargout{1:nargout}] = iDynTreeMEX(1263, self, varargin{:});
    end
    function varargout = isConsistent(self,varargin)
      [varargout{1:nargout}] = iDynTreeMEX(1264, self, varargin{:});
=======
      [varargout{1:nargout}] = iDynTreeMEX(1241, self, varargin{:});
    end
    function varargout = isConsistent(self,varargin)
      [varargout{1:nargout}] = iDynTreeMEX(1242, self, varargin{:});
>>>>>>> Add autogenerated bindings
    end
    function varargout = S(self, varargin)
      narginchk(1, 2)
      if nargin==1
        nargoutchk(0, 1)
<<<<<<< HEAD
        varargout{1} = iDynTreeMEX(1265, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1266, self, varargin{1});
=======
        varargout{1} = iDynTreeMEX(1243, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1244, self, varargin{1});
>>>>>>> Add autogenerated bindings
      end
    end
    function varargout = U(self, varargin)
      narginchk(1, 2)
      if nargin==1
        nargoutchk(0, 1)
<<<<<<< HEAD
        varargout{1} = iDynTreeMEX(1267, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1268, self, varargin{1});
=======
        varargout{1} = iDynTreeMEX(1245, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1246, self, varargin{1});
>>>>>>> Add autogenerated bindings
      end
    end
    function varargout = D(self, varargin)
      narginchk(1, 2)
      if nargin==1
        nargoutchk(0, 1)
<<<<<<< HEAD
        varargout{1} = iDynTreeMEX(1269, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1270, self, varargin{1});
=======
        varargout{1} = iDynTreeMEX(1247, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1248, self, varargin{1});
>>>>>>> Add autogenerated bindings
      end
    end
    function varargout = u(self, varargin)
      narginchk(1, 2)
      if nargin==1
        nargoutchk(0, 1)
<<<<<<< HEAD
        varargout{1} = iDynTreeMEX(1271, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1272, self, varargin{1});
=======
        varargout{1} = iDynTreeMEX(1249, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1250, self, varargin{1});
>>>>>>> Add autogenerated bindings
      end
    end
    function varargout = linksVel(self, varargin)
      narginchk(1, 2)
      if nargin==1
        nargoutchk(0, 1)
<<<<<<< HEAD
        varargout{1} = iDynTreeMEX(1273, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1274, self, varargin{1});
=======
        varargout{1} = iDynTreeMEX(1251, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1252, self, varargin{1});
>>>>>>> Add autogenerated bindings
      end
    end
    function varargout = linksBiasAcceleration(self, varargin)
      narginchk(1, 2)
      if nargin==1
        nargoutchk(0, 1)
<<<<<<< HEAD
        varargout{1} = iDynTreeMEX(1275, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1276, self, varargin{1});
=======
        varargout{1} = iDynTreeMEX(1253, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1254, self, varargin{1});
>>>>>>> Add autogenerated bindings
      end
    end
    function varargout = linksAccelerations(self, varargin)
      narginchk(1, 2)
      if nargin==1
        nargoutchk(0, 1)
<<<<<<< HEAD
        varargout{1} = iDynTreeMEX(1277, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1278, self, varargin{1});
=======
        varargout{1} = iDynTreeMEX(1255, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1256, self, varargin{1});
>>>>>>> Add autogenerated bindings
      end
    end
    function varargout = linkABIs(self, varargin)
      narginchk(1, 2)
      if nargin==1
        nargoutchk(0, 1)
<<<<<<< HEAD
        varargout{1} = iDynTreeMEX(1279, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1280, self, varargin{1});
=======
        varargout{1} = iDynTreeMEX(1257, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1258, self, varargin{1});
>>>>>>> Add autogenerated bindings
      end
    end
    function varargout = linksBiasWrench(self, varargin)
      narginchk(1, 2)
      if nargin==1
        nargoutchk(0, 1)
<<<<<<< HEAD
        varargout{1} = iDynTreeMEX(1281, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1282, self, varargin{1});
=======
        varargout{1} = iDynTreeMEX(1259, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1260, self, varargin{1});
>>>>>>> Add autogenerated bindings
      end
    end
    function delete(self)
      if self.swigPtr
<<<<<<< HEAD
        iDynTreeMEX(1283, self);
=======
        iDynTreeMEX(1261, self);
>>>>>>> Add autogenerated bindings
        self.SwigClear();
      end
    end
  end
  methods(Static)
  end
end
