classdef BerdyOptions < SwigRef
  methods
    function this = swig_this(self)
      this = iDynTreeMEX(3, self);
    end
    function self = BerdyOptions(varargin)
      if nargin==1 && strcmp(class(varargin{1}),'SwigRef')
        if ~isnull(varargin{1})
          self.swigPtr = varargin{1}.swigPtr;
        end
      else
<<<<<<< HEAD
        tmp = iDynTreeMEX(1541, varargin{:});
=======
        tmp = iDynTreeMEX(1528, varargin{:});
>>>>>>> Add autogenerated bindings
        self.swigPtr = tmp.swigPtr;
        tmp.SwigClear();
      end
    end
    function varargout = berdyVariant(self, varargin)
      narginchk(1, 2)
      if nargin==1
        nargoutchk(0, 1)
<<<<<<< HEAD
        varargout{1} = iDynTreeMEX(1542, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1543, self, varargin{1});
=======
        varargout{1} = iDynTreeMEX(1529, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1530, self, varargin{1});
>>>>>>> Add autogenerated bindings
      end
    end
    function varargout = includeAllNetExternalWrenchesAsDynamicVariables(self, varargin)
      narginchk(1, 2)
      if nargin==1
        nargoutchk(0, 1)
<<<<<<< HEAD
        varargout{1} = iDynTreeMEX(1544, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1545, self, varargin{1});
=======
        varargout{1} = iDynTreeMEX(1531, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1532, self, varargin{1});
>>>>>>> Add autogenerated bindings
      end
    end
    function varargout = includeAllJointAccelerationsAsSensors(self, varargin)
      narginchk(1, 2)
      if nargin==1
        nargoutchk(0, 1)
<<<<<<< HEAD
        varargout{1} = iDynTreeMEX(1546, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1547, self, varargin{1});
=======
        varargout{1} = iDynTreeMEX(1533, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1534, self, varargin{1});
>>>>>>> Add autogenerated bindings
      end
    end
    function varargout = includeAllJointTorquesAsSensors(self, varargin)
      narginchk(1, 2)
      if nargin==1
        nargoutchk(0, 1)
<<<<<<< HEAD
        varargout{1} = iDynTreeMEX(1548, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1549, self, varargin{1});
=======
        varargout{1} = iDynTreeMEX(1535, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1536, self, varargin{1});
>>>>>>> Add autogenerated bindings
      end
    end
    function varargout = includeAllNetExternalWrenchesAsSensors(self, varargin)
      narginchk(1, 2)
      if nargin==1
        nargoutchk(0, 1)
<<<<<<< HEAD
        varargout{1} = iDynTreeMEX(1550, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1551, self, varargin{1});
=======
        varargout{1} = iDynTreeMEX(1537, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1538, self, varargin{1});
>>>>>>> Add autogenerated bindings
      end
    end
    function varargout = includeFixedBaseExternalWrench(self, varargin)
      narginchk(1, 2)
      if nargin==1
        nargoutchk(0, 1)
<<<<<<< HEAD
        varargout{1} = iDynTreeMEX(1552, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1553, self, varargin{1});
=======
        varargout{1} = iDynTreeMEX(1539, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1540, self, varargin{1});
>>>>>>> Add autogenerated bindings
      end
    end
    function varargout = jointOnWhichTheInternalWrenchIsMeasured(self, varargin)
      narginchk(1, 2)
      if nargin==1
        nargoutchk(0, 1)
<<<<<<< HEAD
        varargout{1} = iDynTreeMEX(1554, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1555, self, varargin{1});
=======
        varargout{1} = iDynTreeMEX(1541, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1542, self, varargin{1});
>>>>>>> Add autogenerated bindings
      end
    end
    function varargout = baseLink(self, varargin)
      narginchk(1, 2)
      if nargin==1
        nargoutchk(0, 1)
<<<<<<< HEAD
        varargout{1} = iDynTreeMEX(1556, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1557, self, varargin{1});
      end
    end
    function varargout = checkConsistency(self,varargin)
      [varargout{1:nargout}] = iDynTreeMEX(1558, self, varargin{:});
    end
    function delete(self)
      if self.swigPtr
        iDynTreeMEX(1559, self);
=======
        varargout{1} = iDynTreeMEX(1543, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1544, self, varargin{1});
      end
    end
    function varargout = checkConsistency(self,varargin)
      [varargout{1:nargout}] = iDynTreeMEX(1545, self, varargin{:});
    end
    function delete(self)
      if self.swigPtr
        iDynTreeMEX(1546, self);
>>>>>>> Add autogenerated bindings
        self.SwigClear();
      end
    end
  end
  methods(Static)
  end
end
