classdef BerdyDynamicVariable < SwigRef
  methods
    function this = swig_this(self)
      this = iDynTreeMEX(3, self);
    end
    function varargout = type(self, varargin)
      narginchk(1, 2)
      if nargin==1
        nargoutchk(0, 1)
<<<<<<< HEAD
        varargout{1} = iDynTreeMEX(1570, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1571, self, varargin{1});
=======
        varargout{1} = iDynTreeMEX(1557, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1558, self, varargin{1});
>>>>>>> Add autogenerated bindings
      end
    end
    function varargout = id(self, varargin)
      narginchk(1, 2)
      if nargin==1
        nargoutchk(0, 1)
<<<<<<< HEAD
        varargout{1} = iDynTreeMEX(1572, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1573, self, varargin{1});
=======
        varargout{1} = iDynTreeMEX(1559, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1560, self, varargin{1});
>>>>>>> Add autogenerated bindings
      end
    end
    function varargout = range(self, varargin)
      narginchk(1, 2)
      if nargin==1
        nargoutchk(0, 1)
<<<<<<< HEAD
        varargout{1} = iDynTreeMEX(1574, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1575, self, varargin{1});
      end
    end
    function varargout = eq(self,varargin)
      [varargout{1:nargout}] = iDynTreeMEX(1576, self, varargin{:});
    end
    function varargout = lt(self,varargin)
      [varargout{1:nargout}] = iDynTreeMEX(1577, self, varargin{:});
=======
        varargout{1} = iDynTreeMEX(1561, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1562, self, varargin{1});
      end
    end
    function varargout = eq(self,varargin)
      [varargout{1:nargout}] = iDynTreeMEX(1563, self, varargin{:});
    end
    function varargout = lt(self,varargin)
      [varargout{1:nargout}] = iDynTreeMEX(1564, self, varargin{:});
>>>>>>> Add autogenerated bindings
    end
    function self = BerdyDynamicVariable(varargin)
      if nargin==1 && strcmp(class(varargin{1}),'SwigRef')
        if ~isnull(varargin{1})
          self.swigPtr = varargin{1}.swigPtr;
        end
      else
<<<<<<< HEAD
        tmp = iDynTreeMEX(1578, varargin{:});
=======
        tmp = iDynTreeMEX(1565, varargin{:});
>>>>>>> Add autogenerated bindings
        self.swigPtr = tmp.swigPtr;
        tmp.SwigClear();
      end
    end
    function delete(self)
      if self.swigPtr
<<<<<<< HEAD
        iDynTreeMEX(1579, self);
=======
        iDynTreeMEX(1566, self);
>>>>>>> Add autogenerated bindings
        self.SwigClear();
      end
    end
  end
  methods(Static)
  end
end
