classdef BerdySensor < SwigRef
  methods
    function this = swig_this(self)
      this = iDynTreeMEX(3, self);
    end
    function varargout = type(self, varargin)
      narginchk(1, 2)
      if nargin==1
        nargoutchk(0, 1)
<<<<<<< HEAD
        varargout{1} = iDynTreeMEX(1560, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1561, self, varargin{1});
=======
        varargout{1} = iDynTreeMEX(1547, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1548, self, varargin{1});
>>>>>>> Add autogenerated bindings
      end
    end
    function varargout = id(self, varargin)
      narginchk(1, 2)
      if nargin==1
        nargoutchk(0, 1)
<<<<<<< HEAD
        varargout{1} = iDynTreeMEX(1562, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1563, self, varargin{1});
=======
        varargout{1} = iDynTreeMEX(1549, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1550, self, varargin{1});
>>>>>>> Add autogenerated bindings
      end
    end
    function varargout = range(self, varargin)
      narginchk(1, 2)
      if nargin==1
        nargoutchk(0, 1)
<<<<<<< HEAD
        varargout{1} = iDynTreeMEX(1564, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1565, self, varargin{1});
      end
    end
    function varargout = eq(self,varargin)
      [varargout{1:nargout}] = iDynTreeMEX(1566, self, varargin{:});
    end
    function varargout = lt(self,varargin)
      [varargout{1:nargout}] = iDynTreeMEX(1567, self, varargin{:});
=======
        varargout{1} = iDynTreeMEX(1551, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1552, self, varargin{1});
      end
    end
    function varargout = eq(self,varargin)
      [varargout{1:nargout}] = iDynTreeMEX(1553, self, varargin{:});
    end
    function varargout = lt(self,varargin)
      [varargout{1:nargout}] = iDynTreeMEX(1554, self, varargin{:});
>>>>>>> Add autogenerated bindings
    end
    function self = BerdySensor(varargin)
      if nargin==1 && strcmp(class(varargin{1}),'SwigRef')
        if ~isnull(varargin{1})
          self.swigPtr = varargin{1}.swigPtr;
        end
      else
<<<<<<< HEAD
        tmp = iDynTreeMEX(1568, varargin{:});
=======
        tmp = iDynTreeMEX(1555, varargin{:});
>>>>>>> Add autogenerated bindings
        self.swigPtr = tmp.swigPtr;
        tmp.SwigClear();
      end
    end
    function delete(self)
      if self.swigPtr
<<<<<<< HEAD
        iDynTreeMEX(1569, self);
=======
        iDynTreeMEX(1556, self);
>>>>>>> Add autogenerated bindings
        self.SwigClear();
      end
    end
  end
  methods(Static)
  end
end
