classdef ColorViz < SwigRef
  methods
    function this = swig_this(self)
      this = iDynTreeMEX(3, self);
    end
    function varargout = r(self, varargin)
      narginchk(1, 2)
      if nargin==1
        nargoutchk(0, 1)
<<<<<<< HEAD
        varargout{1} = iDynTreeMEX(1855, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1856, self, varargin{1});
=======
        varargout{1} = iDynTreeMEX(1724, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1725, self, varargin{1});
>>>>>>> Add autogenerated bindings
      end
    end
    function varargout = g(self, varargin)
      narginchk(1, 2)
      if nargin==1
        nargoutchk(0, 1)
<<<<<<< HEAD
        varargout{1} = iDynTreeMEX(1857, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1858, self, varargin{1});
=======
        varargout{1} = iDynTreeMEX(1726, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1727, self, varargin{1});
>>>>>>> Add autogenerated bindings
      end
    end
    function varargout = b(self, varargin)
      narginchk(1, 2)
      if nargin==1
        nargoutchk(0, 1)
<<<<<<< HEAD
        varargout{1} = iDynTreeMEX(1859, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1860, self, varargin{1});
=======
        varargout{1} = iDynTreeMEX(1728, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1729, self, varargin{1});
>>>>>>> Add autogenerated bindings
      end
    end
    function varargout = a(self, varargin)
      narginchk(1, 2)
      if nargin==1
        nargoutchk(0, 1)
<<<<<<< HEAD
        varargout{1} = iDynTreeMEX(1861, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1862, self, varargin{1});
=======
        varargout{1} = iDynTreeMEX(1730, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1731, self, varargin{1});
>>>>>>> Add autogenerated bindings
      end
    end
    function self = ColorViz(varargin)
      if nargin==1 && strcmp(class(varargin{1}),'SwigRef')
        if ~isnull(varargin{1})
          self.swigPtr = varargin{1}.swigPtr;
        end
      else
<<<<<<< HEAD
        tmp = iDynTreeMEX(1863, varargin{:});
=======
        tmp = iDynTreeMEX(1732, varargin{:});
>>>>>>> Add autogenerated bindings
        self.swigPtr = tmp.swigPtr;
        tmp.SwigClear();
      end
    end
    function delete(self)
      if self.swigPtr
<<<<<<< HEAD
        iDynTreeMEX(1864, self);
=======
        iDynTreeMEX(1733, self);
>>>>>>> Add autogenerated bindings
        self.SwigClear();
      end
    end
  end
  methods(Static)
  end
end
