function varargout = computeLinkNetWrenchesWithoutGravity(varargin)
<<<<<<< HEAD
  [varargout{1:nargout}] = iDynTreeMEX(1511, varargin{:});
=======
  [varargout{1:nargout}] = iDynTreeMEX(1498, varargin{:});
>>>>>>> Add autogenerated bindings
end
