function varargout = ComputeLinearAndAngularMomentum(varargin)
<<<<<<< HEAD
  [varargout{1:nargout}] = iDynTreeMEX(1258, varargin{:});
=======
  [varargout{1:nargout}] = iDynTreeMEX(1236, varargin{:});
>>>>>>> Add autogenerated bindings
end
