function varargout = ComputeLinearAndAngularMomentumDerivativeBias(varargin)
<<<<<<< HEAD
  [varargout{1:nargout}] = iDynTreeMEX(1259, varargin{:});
=======
  [varargout{1:nargout}] = iDynTreeMEX(1237, varargin{:});
>>>>>>> Add autogenerated bindings
end
