function varargout = CompositeRigidBodyAlgorithm(varargin)
<<<<<<< HEAD
  [varargout{1:nargout}] = iDynTreeMEX(1261, varargin{:});
=======
  [varargout{1:nargout}] = iDynTreeMEX(1239, varargin{:});
>>>>>>> Add autogenerated bindings
end
