function varargout = dofsListFromURDF(varargin)
<<<<<<< HEAD
  [varargout{1:nargout}] = iDynTreeMEX(1444, varargin{:});
=======
  [varargout{1:nargout}] = iDynTreeMEX(1422, varargin{:});
>>>>>>> Add autogenerated bindings
end
