function varargout = dofsListFromURDFString(varargin)
<<<<<<< HEAD
  [varargout{1:nargout}] = iDynTreeMEX(1445, varargin{:});
=======
  [varargout{1:nargout}] = iDynTreeMEX(1423, varargin{:});
>>>>>>> Add autogenerated bindings
end
