function varargout = dynamicsEstimationForwardVelAccKinematics(varargin)
<<<<<<< HEAD
  [varargout{1:nargout}] = iDynTreeMEX(1509, varargin{:});
=======
  [varargout{1:nargout}] = iDynTreeMEX(1496, varargin{:});
>>>>>>> Add autogenerated bindings
end
