function varargout = dynamicsEstimationForwardVelKinematics(varargin)
<<<<<<< HEAD
  [varargout{1:nargout}] = iDynTreeMEX(1510, varargin{:});
=======
  [varargout{1:nargout}] = iDynTreeMEX(1497, varargin{:});
>>>>>>> Add autogenerated bindings
end
