classdef DynamicsRegressorParameter < SwigRef
  methods
    function this = swig_this(self)
      this = iDynTreeMEX(3, self);
    end
    function varargout = category(self, varargin)
      narginchk(1, 2)
      if nargin==1
        nargoutchk(0, 1)
<<<<<<< HEAD
        varargout{1} = iDynTreeMEX(1746, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1747, self, varargin{1});
=======
        varargout{1} = iDynTreeMEX(1615, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1616, self, varargin{1});
>>>>>>> Add autogenerated bindings
      end
    end
    function varargout = elemIndex(self, varargin)
      narginchk(1, 2)
      if nargin==1
        nargoutchk(0, 1)
<<<<<<< HEAD
        varargout{1} = iDynTreeMEX(1748, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1749, self, varargin{1});
=======
        varargout{1} = iDynTreeMEX(1617, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1618, self, varargin{1});
>>>>>>> Add autogenerated bindings
      end
    end
    function varargout = type(self, varargin)
      narginchk(1, 2)
      if nargin==1
        nargoutchk(0, 1)
<<<<<<< HEAD
        varargout{1} = iDynTreeMEX(1750, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1751, self, varargin{1});
      end
    end
    function varargout = lt(self,varargin)
      [varargout{1:nargout}] = iDynTreeMEX(1752, self, varargin{:});
    end
    function varargout = eq(self,varargin)
      [varargout{1:nargout}] = iDynTreeMEX(1753, self, varargin{:});
    end
    function varargout = ne(self,varargin)
      [varargout{1:nargout}] = iDynTreeMEX(1754, self, varargin{:});
=======
        varargout{1} = iDynTreeMEX(1619, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1620, self, varargin{1});
      end
    end
    function varargout = lt(self,varargin)
      [varargout{1:nargout}] = iDynTreeMEX(1621, self, varargin{:});
    end
    function varargout = eq(self,varargin)
      [varargout{1:nargout}] = iDynTreeMEX(1622, self, varargin{:});
    end
    function varargout = ne(self,varargin)
      [varargout{1:nargout}] = iDynTreeMEX(1623, self, varargin{:});
>>>>>>> Add autogenerated bindings
    end
    function self = DynamicsRegressorParameter(varargin)
      if nargin==1 && strcmp(class(varargin{1}),'SwigRef')
        if ~isnull(varargin{1})
          self.swigPtr = varargin{1}.swigPtr;
        end
      else
<<<<<<< HEAD
        tmp = iDynTreeMEX(1755, varargin{:});
=======
        tmp = iDynTreeMEX(1624, varargin{:});
>>>>>>> Add autogenerated bindings
        self.swigPtr = tmp.swigPtr;
        tmp.SwigClear();
      end
    end
    function delete(self)
      if self.swigPtr
<<<<<<< HEAD
        iDynTreeMEX(1756, self);
=======
        iDynTreeMEX(1625, self);
>>>>>>> Add autogenerated bindings
        self.SwigClear();
      end
    end
  end
  methods(Static)
  end
end
