function varargout = estimateExternalWrenches(varargin)
<<<<<<< HEAD
  [varargout{1:nargout}] = iDynTreeMEX(1508, varargin{:});
=======
  [varargout{1:nargout}] = iDynTreeMEX(1495, varargin{:});
>>>>>>> Add autogenerated bindings
end
