function varargout = estimateLinkContactWrenchesFromLinkNetExternalWrenches(varargin)
<<<<<<< HEAD
  [varargout{1:nargout}] = iDynTreeMEX(1512, varargin{:});
=======
  [varargout{1:nargout}] = iDynTreeMEX(1499, varargin{:});
>>>>>>> Add autogenerated bindings
end
