function varargout = estimateExternalWrenchesWithoutInternalFT(varargin)
<<<<<<< HEAD
  [varargout{1:nargout}] = iDynTreeMEX(1507, varargin{:});
=======
  [varargout{1:nargout}] = iDynTreeMEX(1494, varargin{:});
>>>>>>> Add autogenerated bindings
end
