classdef estimateExternalWrenchesBuffers < SwigRef
  methods
    function this = swig_this(self)
      this = iDynTreeMEX(3, self);
    end
    function self = estimateExternalWrenchesBuffers(varargin)
      if nargin==1 && strcmp(class(varargin{1}),'SwigRef')
        if ~isnull(varargin{1})
          self.swigPtr = varargin{1}.swigPtr;
        end
      else
<<<<<<< HEAD
        tmp = iDynTreeMEX(1489, varargin{:});
=======
        tmp = iDynTreeMEX(1476, varargin{:});
>>>>>>> Add autogenerated bindings
        self.swigPtr = tmp.swigPtr;
        tmp.SwigClear();
      end
    end
    function varargout = resize(self,varargin)
<<<<<<< HEAD
      [varargout{1:nargout}] = iDynTreeMEX(1490, self, varargin{:});
    end
    function varargout = getNrOfSubModels(self,varargin)
      [varargout{1:nargout}] = iDynTreeMEX(1491, self, varargin{:});
    end
    function varargout = getNrOfLinks(self,varargin)
      [varargout{1:nargout}] = iDynTreeMEX(1492, self, varargin{:});
    end
    function varargout = isConsistent(self,varargin)
      [varargout{1:nargout}] = iDynTreeMEX(1493, self, varargin{:});
=======
      [varargout{1:nargout}] = iDynTreeMEX(1477, self, varargin{:});
    end
    function varargout = getNrOfSubModels(self,varargin)
      [varargout{1:nargout}] = iDynTreeMEX(1478, self, varargin{:});
    end
    function varargout = getNrOfLinks(self,varargin)
      [varargout{1:nargout}] = iDynTreeMEX(1479, self, varargin{:});
    end
    function varargout = isConsistent(self,varargin)
      [varargout{1:nargout}] = iDynTreeMEX(1480, self, varargin{:});
>>>>>>> Add autogenerated bindings
    end
    function varargout = A(self, varargin)
      narginchk(1, 2)
      if nargin==1
        nargoutchk(0, 1)
<<<<<<< HEAD
        varargout{1} = iDynTreeMEX(1494, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1495, self, varargin{1});
=======
        varargout{1} = iDynTreeMEX(1481, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1482, self, varargin{1});
>>>>>>> Add autogenerated bindings
      end
    end
    function varargout = x(self, varargin)
      narginchk(1, 2)
      if nargin==1
        nargoutchk(0, 1)
<<<<<<< HEAD
        varargout{1} = iDynTreeMEX(1496, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1497, self, varargin{1});
=======
        varargout{1} = iDynTreeMEX(1483, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1484, self, varargin{1});
>>>>>>> Add autogenerated bindings
      end
    end
    function varargout = b(self, varargin)
      narginchk(1, 2)
      if nargin==1
        nargoutchk(0, 1)
<<<<<<< HEAD
        varargout{1} = iDynTreeMEX(1498, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1499, self, varargin{1});
=======
        varargout{1} = iDynTreeMEX(1485, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1486, self, varargin{1});
>>>>>>> Add autogenerated bindings
      end
    end
    function varargout = pinvA(self, varargin)
      narginchk(1, 2)
      if nargin==1
        nargoutchk(0, 1)
<<<<<<< HEAD
        varargout{1} = iDynTreeMEX(1500, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1501, self, varargin{1});
=======
        varargout{1} = iDynTreeMEX(1487, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1488, self, varargin{1});
>>>>>>> Add autogenerated bindings
      end
    end
    function varargout = b_contacts_subtree(self, varargin)
      narginchk(1, 2)
      if nargin==1
        nargoutchk(0, 1)
<<<<<<< HEAD
        varargout{1} = iDynTreeMEX(1502, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1503, self, varargin{1});
=======
        varargout{1} = iDynTreeMEX(1489, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1490, self, varargin{1});
>>>>>>> Add autogenerated bindings
      end
    end
    function varargout = subModelBase_H_link(self, varargin)
      narginchk(1, 2)
      if nargin==1
        nargoutchk(0, 1)
<<<<<<< HEAD
        varargout{1} = iDynTreeMEX(1504, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1505, self, varargin{1});
=======
        varargout{1} = iDynTreeMEX(1491, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1492, self, varargin{1});
>>>>>>> Add autogenerated bindings
      end
    end
    function delete(self)
      if self.swigPtr
<<<<<<< HEAD
        iDynTreeMEX(1506, self);
=======
        iDynTreeMEX(1493, self);
>>>>>>> Add autogenerated bindings
        self.SwigClear();
      end
    end
  end
  methods(Static)
  end
end
