function varargout = ForwardPositionKinematics(varargin)
<<<<<<< HEAD
  [varargout{1:nargout}] = iDynTreeMEX(1252, varargin{:});
=======
  [varargout{1:nargout}] = iDynTreeMEX(1230, varargin{:});
>>>>>>> Add autogenerated bindings
end
