function varargout = ForwardPosVelKinematics(varargin)
<<<<<<< HEAD
  [varargout{1:nargout}] = iDynTreeMEX(1255, varargin{:});
=======
  [varargout{1:nargout}] = iDynTreeMEX(1233, varargin{:});
>>>>>>> Add autogenerated bindings
end
