function varargout = ForwardPosVelAccKinematics(varargin)
<<<<<<< HEAD
  [varargout{1:nargout}] = iDynTreeMEX(1254, varargin{:});
=======
  [varargout{1:nargout}] = iDynTreeMEX(1232, varargin{:});
>>>>>>> Add autogenerated bindings
end
