function varargout = ForwardVelAccKinematics(varargin)
<<<<<<< HEAD
  [varargout{1:nargout}] = iDynTreeMEX(1253, varargin{:});
=======
  [varargout{1:nargout}] = iDynTreeMEX(1231, varargin{:});
>>>>>>> Add autogenerated bindings
end
