function varargout = ForwardAccKinematics(varargin)
<<<<<<< HEAD
  [varargout{1:nargout}] = iDynTreeMEX(1256, varargin{:});
=======
  [varargout{1:nargout}] = iDynTreeMEX(1234, varargin{:});
>>>>>>> Add autogenerated bindings
end
