function varargout = ForwardBiasAccKinematics(varargin)
<<<<<<< HEAD
  [varargout{1:nargout}] = iDynTreeMEX(1257, varargin{:});
=======
  [varargout{1:nargout}] = iDynTreeMEX(1235, varargin{:});
>>>>>>> Add autogenerated bindings
end
