function varargout = getSensorTypeSize(varargin)
<<<<<<< HEAD
  [varargout{1:nargout}] = iDynTreeMEX(1289, varargin{:});
=======
  [varargout{1:nargout}] = iDynTreeMEX(1267, varargin{:});
>>>>>>> Add autogenerated bindings
end
