function varargout = InverseDynamicsInertialParametersRegressor(varargin)
<<<<<<< HEAD
  [varargout{1:nargout}] = iDynTreeMEX(1285, varargin{:});
=======
  [varargout{1:nargout}] = iDynTreeMEX(1263, varargin{:});
>>>>>>> Add autogenerated bindings
end
