function varargout = isDOFBerdyDynamicVariable(varargin)
<<<<<<< HEAD
  [varargout{1:nargout}] = iDynTreeMEX(1540, varargin{:});
=======
  [varargout{1:nargout}] = iDynTreeMEX(1527, varargin{:});
>>>>>>> Add autogenerated bindings
end
