function varargout = isJointBerdyDynamicVariable(varargin)
<<<<<<< HEAD
  [varargout{1:nargout}] = iDynTreeMEX(1539, varargin{:});
=======
  [varargout{1:nargout}] = iDynTreeMEX(1526, varargin{:});
>>>>>>> Add autogenerated bindings
end
