function varargout = isJointSensor(varargin)
<<<<<<< HEAD
  [varargout{1:nargout}] = iDynTreeMEX(1288, varargin{:});
=======
  [varargout{1:nargout}] = iDynTreeMEX(1266, varargin{:});
>>>>>>> Add autogenerated bindings
end
