function varargout = isLinkSensor(varargin)
<<<<<<< HEAD
  [varargout{1:nargout}] = iDynTreeMEX(1287, varargin{:});
=======
  [varargout{1:nargout}] = iDynTreeMEX(1265, varargin{:});
>>>>>>> Add autogenerated bindings
end
