function varargout = isLinkBerdyDynamicVariable(varargin)
<<<<<<< HEAD
  [varargout{1:nargout}] = iDynTreeMEX(1538, varargin{:});
=======
  [varargout{1:nargout}] = iDynTreeMEX(1525, varargin{:});
>>>>>>> Add autogenerated bindings
end
