function varargout = modelFromURDF(varargin)
<<<<<<< HEAD
  [varargout{1:nargout}] = iDynTreeMEX(1442, varargin{:});
=======
  [varargout{1:nargout}] = iDynTreeMEX(1420, varargin{:});
>>>>>>> Add autogenerated bindings
end
