function varargout = modelFromURDFString(varargin)
<<<<<<< HEAD
  [varargout{1:nargout}] = iDynTreeMEX(1443, varargin{:});
=======
  [varargout{1:nargout}] = iDynTreeMEX(1421, varargin{:});
>>>>>>> Add autogenerated bindings
end
