function varargout = predictSensorsMeasurements(varargin)
<<<<<<< HEAD
  [varargout{1:nargout}] = iDynTreeMEX(1434, varargin{:});
=======
  [varargout{1:nargout}] = iDynTreeMEX(1412, varargin{:});
>>>>>>> Add autogenerated bindings
end
