function varargout = predictSensorsMeasurementsFromRawBuffers(varargin)
<<<<<<< HEAD
  [varargout{1:nargout}] = iDynTreeMEX(1435, varargin{:});
=======
  [varargout{1:nargout}] = iDynTreeMEX(1413, varargin{:});
>>>>>>> Add autogenerated bindings
end
