function varargout = RNEADynamicPhase(varargin)
<<<<<<< HEAD
  [varargout{1:nargout}] = iDynTreeMEX(1260, varargin{:});
=======
  [varargout{1:nargout}] = iDynTreeMEX(1238, varargin{:});
>>>>>>> Add autogenerated bindings
end
