function varargout = sensorsFromURDF(varargin)
<<<<<<< HEAD
  [varargout{1:nargout}] = iDynTreeMEX(1446, varargin{:});
=======
  [varargout{1:nargout}] = iDynTreeMEX(1424, varargin{:});
>>>>>>> Add autogenerated bindings
end
