function varargout = sensorsFromURDFString(varargin)
<<<<<<< HEAD
  [varargout{1:nargout}] = iDynTreeMEX(1447, varargin{:});
=======
  [varargout{1:nargout}] = iDynTreeMEX(1425, varargin{:});
>>>>>>> Add autogenerated bindings
end
