classdef UnknownWrenchContact < SwigRef
  methods
    function this = swig_this(self)
      this = iDynTreeMEX(3, self);
    end
    function self = UnknownWrenchContact(varargin)
      if nargin==1 && strcmp(class(varargin{1}),'SwigRef')
        if ~isnull(varargin{1})
          self.swigPtr = varargin{1}.swigPtr;
        end
      else
<<<<<<< HEAD
        tmp = iDynTreeMEX(1466, varargin{:});
=======
        tmp = iDynTreeMEX(1453, varargin{:});
>>>>>>> Add autogenerated bindings
        self.swigPtr = tmp.swigPtr;
        tmp.SwigClear();
      end
    end
    function varargout = unknownType(self, varargin)
      narginchk(1, 2)
      if nargin==1
        nargoutchk(0, 1)
<<<<<<< HEAD
        varargout{1} = iDynTreeMEX(1467, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1468, self, varargin{1});
=======
        varargout{1} = iDynTreeMEX(1454, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1455, self, varargin{1});
>>>>>>> Add autogenerated bindings
      end
    end
    function varargout = contactPoint(self, varargin)
      narginchk(1, 2)
      if nargin==1
        nargoutchk(0, 1)
<<<<<<< HEAD
        varargout{1} = iDynTreeMEX(1469, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1470, self, varargin{1});
=======
        varargout{1} = iDynTreeMEX(1456, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1457, self, varargin{1});
>>>>>>> Add autogenerated bindings
      end
    end
    function varargout = forceDirection(self, varargin)
      narginchk(1, 2)
      if nargin==1
        nargoutchk(0, 1)
<<<<<<< HEAD
        varargout{1} = iDynTreeMEX(1471, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1472, self, varargin{1});
=======
        varargout{1} = iDynTreeMEX(1458, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1459, self, varargin{1});
>>>>>>> Add autogenerated bindings
      end
    end
    function varargout = knownWrench(self, varargin)
      narginchk(1, 2)
      if nargin==1
        nargoutchk(0, 1)
<<<<<<< HEAD
        varargout{1} = iDynTreeMEX(1473, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1474, self, varargin{1});
=======
        varargout{1} = iDynTreeMEX(1460, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1461, self, varargin{1});
>>>>>>> Add autogenerated bindings
      end
    end
    function varargout = contactId(self, varargin)
      narginchk(1, 2)
      if nargin==1
        nargoutchk(0, 1)
<<<<<<< HEAD
        varargout{1} = iDynTreeMEX(1475, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1476, self, varargin{1});
=======
        varargout{1} = iDynTreeMEX(1462, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1463, self, varargin{1});
>>>>>>> Add autogenerated bindings
      end
    end
    function delete(self)
      if self.swigPtr
<<<<<<< HEAD
        iDynTreeMEX(1477, self);
=======
        iDynTreeMEX(1464, self);
>>>>>>> Add autogenerated bindings
        self.SwigClear();
      end
    end
  end
  methods(Static)
  end
end
