classdef URDFParserOptions < SwigRef
  methods
    function this = swig_this(self)
      this = iDynTreeMEX(3, self);
    end
    function varargout = addSensorFramesAsAdditionalFrames(self, varargin)
      narginchk(1, 2)
      if nargin==1
        nargoutchk(0, 1)
<<<<<<< HEAD
        varargout{1} = iDynTreeMEX(1436, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1437, self, varargin{1});
=======
        varargout{1} = iDynTreeMEX(1414, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1415, self, varargin{1});
>>>>>>> Add autogenerated bindings
      end
    end
    function varargout = originalFilename(self, varargin)
      narginchk(1, 2)
      if nargin==1
        nargoutchk(0, 1)
<<<<<<< HEAD
        varargout{1} = iDynTreeMEX(1438, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1439, self, varargin{1});
=======
        varargout{1} = iDynTreeMEX(1416, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1417, self, varargin{1});
>>>>>>> Add autogenerated bindings
      end
    end
    function self = URDFParserOptions(varargin)
      if nargin==1 && strcmp(class(varargin{1}),'SwigRef')
        if ~isnull(varargin{1})
          self.swigPtr = varargin{1}.swigPtr;
        end
      else
<<<<<<< HEAD
        tmp = iDynTreeMEX(1440, varargin{:});
=======
        tmp = iDynTreeMEX(1418, varargin{:});
>>>>>>> Add autogenerated bindings
        self.swigPtr = tmp.swigPtr;
        tmp.SwigClear();
      end
    end
    function delete(self)
      if self.swigPtr
<<<<<<< HEAD
        iDynTreeMEX(1441, self);
=======
        iDynTreeMEX(1419, self);
>>>>>>> Add autogenerated bindings
        self.SwigClear();
      end
    end
  end
  methods(Static)
  end
end
