classdef VisualizerOptions < SwigRef
  methods
    function this = swig_this(self)
      this = iDynTreeMEX(3, self);
    end
    function varargout = verbose(self, varargin)
      narginchk(1, 2)
      if nargin==1
        nargoutchk(0, 1)
<<<<<<< HEAD
        varargout{1} = iDynTreeMEX(1920, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1921, self, varargin{1});
=======
        varargout{1} = iDynTreeMEX(1778, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1779, self, varargin{1});
>>>>>>> Add autogenerated bindings
      end
    end
    function varargout = winWidth(self, varargin)
      narginchk(1, 2)
      if nargin==1
        nargoutchk(0, 1)
<<<<<<< HEAD
        varargout{1} = iDynTreeMEX(1922, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1923, self, varargin{1});
=======
        varargout{1} = iDynTreeMEX(1780, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1781, self, varargin{1});
>>>>>>> Add autogenerated bindings
      end
    end
    function varargout = winHeight(self, varargin)
      narginchk(1, 2)
      if nargin==1
        nargoutchk(0, 1)
<<<<<<< HEAD
        varargout{1} = iDynTreeMEX(1924, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1925, self, varargin{1});
=======
        varargout{1} = iDynTreeMEX(1782, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1783, self, varargin{1});
>>>>>>> Add autogenerated bindings
      end
    end
    function varargout = rootFrameArrowsDimension(self, varargin)
      narginchk(1, 2)
      if nargin==1
        nargoutchk(0, 1)
<<<<<<< HEAD
        varargout{1} = iDynTreeMEX(1926, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1927, self, varargin{1});
=======
        varargout{1} = iDynTreeMEX(1784, self);
      else
        nargoutchk(0, 0)
        iDynTreeMEX(1785, self, varargin{1});
>>>>>>> Add autogenerated bindings
      end
    end
    function self = VisualizerOptions(varargin)
      if nargin==1 && strcmp(class(varargin{1}),'SwigRef')
        if ~isnull(varargin{1})
          self.swigPtr = varargin{1}.swigPtr;
        end
      else
<<<<<<< HEAD
        tmp = iDynTreeMEX(1928, varargin{:});
=======
        tmp = iDynTreeMEX(1786, varargin{:});
>>>>>>> Add autogenerated bindings
        self.swigPtr = tmp.swigPtr;
        tmp.SwigClear();
      end
    end
    function delete(self)
      if self.swigPtr
<<<<<<< HEAD
        iDynTreeMEX(1929, self);
=======
        iDynTreeMEX(1787, self);
>>>>>>> Add autogenerated bindings
        self.SwigClear();
      end
    end
  end
  methods(Static)
  end
end
