/*
 * Copyright (C) 2015 Fondazione Istituto Italiano di Tecnologia
 * Authors: Silvio Traversaro, Nuno Guedelha
 * CopyPolicy: Released under the terms of the LGPLv2.1 or later, see LGPL.TXT
 *
 */

#include "AngularForceVector3.cpp"
#include "AngularMotionVector3.cpp"
#include "ArticulatedBodyInertia.cpp"
#include "Axis.cpp"
#include "ClassicalAcc.cpp"
#include "Direction.cpp"
#include "ForceVector3.cpp"
#include "GeomVector3.cpp"
#include "LinearForceVector3.cpp"
#include "LinearMotionVector3.cpp"
#include "MatrixDynSize.cpp"
#include "MotionVector3.cpp"
#include "Position.cpp"
#include "PositionRaw.cpp"
#include "PositionSemantics.cpp"
#include "PrivateUtils.cpp"
#include "Rotation.cpp"
#include "RotationalInertiaRaw.cpp"
#include "RotationRaw.cpp"
#include "RotationSemantics.cpp"
#include "SpatialAcc.cpp"
#include "SpatialForceVector.cpp"
#include "SpatialInertia.cpp"
#include "SpatialInertiaRaw.cpp"
#include "SpatialMomentum.cpp"
#include "SpatialMotionVector.cpp"
#include "TestUtils.cpp"
#include "Transform.cpp"
#include "TransformSemantics.cpp"
#include "Twist.cpp"
#include "Utils.cpp"
#include "VectorDynSize.cpp"
#include "Wrench.cpp"